# Generated by Django 4.2.4 on 2023-09-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0003_uploadartdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadartdetail',
            name='art_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadartdetail',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadartdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='uploadartdetail',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadartdetail',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
