# Generated by Django 4.2.4 on 2023-09-10 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0004_alter_uploadartdetail_art_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadartdetail',
            name='certificate',
            field=models.FileField(blank=True, upload_to='art_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='uploadartdetail',
            name='image',
            field=models.ImageField(blank=True, upload_to='art_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
