# Generated by Django 4.2.4 on 2023-09-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0007_uploadartdetail_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadartdetail',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='uploadartdetail',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
    ]
