# Generated by Django 4.2.4 on 2023-09-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0008_remove_uploadartdetail_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadartdetail',
            name='status',
        ),
        migrations.AddField(
            model_name='uploadartdetail',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
