# Generated by Django 4.2.4 on 2023-09-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0009_remove_uploadartdetail_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadartdetail',
            name='is_approved',
        ),
    ]
