# Generated by Django 4.2.4 on 2023-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0010_remove_uploadartdetail_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadartdetail',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
