# Generated by Django 4.2.4 on 2023-09-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0012_uploadartdetail_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadartdetail',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
