# Generated by Django 4.2.4 on 2023-09-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0013_uploadartdetail_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadartdetail',
            name='is_deleted',
        ),
    ]
